name: Build and Test

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    strategy:
      matrix:
        node-version: [20.x]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      id: pnpm-install
      with:
        version: latest
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: pnpm

    - name: Build
      env:
        CI: true
      run: pnpm build
